// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/Library/About.vue')['default']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ContentMenu: typeof import('./src/components/contentMenu.vue')['default']
    EnglishNews: typeof import('./src/components/EnglishNews.vue')['default']
    EPUBV: typeof import('./src/components/Library/EPUBV.vue')['default']
    HomeNavigator: typeof import('./src/components/HomeNavigator.vue')['default']
    HomePageHeader: typeof import('./src/components/HomePageHeader.vue')['default']
    LibraryNavigator: typeof import('./src/components/Library/LibraryNavigator.vue')['default']
    LibraryPageHeader: typeof import('./src/components/Library/LibraryPageHeader.vue')['default']
    LiteratureNews: typeof import('./src/components/LiteratureNews.vue')['default']
    NewNews: typeof import('./src/components/NewNews.vue')['default']
    PDFV: typeof import('./src/components/Library/PDFV.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScienceNews: typeof import('./src/components/ScienceNews.vue')['default']
    TXTV: typeof import('./src/components/Library/TXTV.vue')['default']
  }
}

export {}
